### ISSUE TITLE
Security concerns

### ISSUE THREAD

**Issue by GiorgiBeriashvili** [St3althyy/java-file-func#1]
This repository contains code too grandiose for non-intellectual (human) individuals to fathom, albeit the colossal minds can leverage the said project to an extent of a potential cataclysmic event.

Per my thought process, an assembly of life experts should review the contents of this repository in order to cumulatively reach a point of understanding, - deeming whether or not such an immaculate creation be shared publicly or not.

**Comment by St3althyy** [comment]
Fixed
